### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by drewnoakes** [melytc/SettingsProject#7]
## features
- [x] ability to rename launch profile
  - [x] select all text and focus on command
  - [x] accept on enter
  - [x] accept on lost focus
  - [x] cancel on escape
- [x] "new" dropdown command implementation @melytc 
- [x] "delete" button
- [x] "copy" button
  - [x] clone data
  - [x] wire up dependencies between properties @drewnoakes 
- [x] hyperlink from property page to launch profiles window
- [x] editor metadata
  - [x] link action kind
    - [x] URL
    - [x] named action (eg. "ManageLaunchProfiles"), looked up via registry
- [x] general UI polish
- [x] add more launch profile kinds
  - [x] research them
  - [x] snapshot debugger
  - [x] IIS / IIS Express from web projects
- [x] new editor types
  - [x] file path with browse button
    - [x] wire up behaviour of button, using file dialog
- [x] search terms
- [ ] help URI
- [x] enable control over varying dimensions for setting values
  - [x] add a dimension to a setting's value configuration
  - [x] remove a dimension from a setting's value configuration
  - [x] remove all dimensions from a setting's value configuration
- [ ] supported values for enums
  - [x] move `EnumValues` from `Setting` to `SettingValue`
  - [x] model display value & value
  - [ ] populate dropdowns correctly when changing vary-by dimensions in the UI
  - [x] value may not be one of the supported values
- [ ] evaluated/unevaluated values
  - [x] in data model
  - [ ] in UI
- [x] support multiple editor specifications, with precedence ordering
- [x] comparers for all immutable dictionaries

## bugs
- [x] Use `&` in UI when combining dimensions, not `|`
- [ ] duplicate launch profile name selection
  - [ ] duplicate a duplicate, end up with "(2) (2)" suffix
  - [ ] duplicate a profile twice, end up with two "(2)" suffixes 
- [ ] fix top/bottom padding in SettingsList control
- [ ] icons in "new" drop down are missing, except last
- [ ] conditionality can break in launch profile view (e.g. 'Use remote debugging')
- [x] enforce ordering of dimensions when multiple selected
- [x] Settings list's scroll viewer should move to top when changing selected launch profile

## design improvements
- [x] replace `IsNavigable` with `Padding`?
- [x] convert `SettingsList` from `UserControl` to `Control`?
- [x] use `Microsoft.VisualStudio.Validation`
- [x] extract immutable setting data to `SettingMetadata`
- [x] remove modification state tracking
- [x] simplify `Setting` and `SettingValue` type hierarchies
- [x] stop checkbox showing description twice (casualty of simplification) @drewnoakes 
- [x] flatten `LinkAction` into `Setting` class, so we have a single type for all settings
- [x] model configured/unconfigured values in the same way, with a dimensions array
- [ ] improve visibility of link/button from property pages to launch profiles UI
- [ ] hide category label in `SettingsList` and `NavigationTree` when page has a single category
- [x] show configuration popup on left click, not right click
  - [x] a templated `Menu` might be better here

## documentation
- [ ] api documentation
- [ ] conceptual docs
  - [ ] adding a property to an existing profile kind
  - [ ] adding a new editor type
  - [ ] adding a new profile kind
